### ISSUE TITLE
error 502 Server Error: Bad Gateway

### ISSUE THREAD

**Issue by mehr-licht** [Ensembl/ensembl-rest#488]
I'm getting this error for the last 24h
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://rest.ensembl.org/lookup/id/ENSG00000157764?expand=1
```

This was using an example in [https://rest.ensembl.org/documentation/info/lookup](https://rest.ensembl.org/documentation/info/lookup):
```
import requests, sys

server = "https://rest.ensembl.org"
ext = "/lookup/id/ENSG00000157764?expand=1"
 
r = requests.get(server+ext, headers={ "Content-Type" : "application/json"})
  
if not r.ok:
   r.raise_for_status()
``` 

Ocasionally I get a good response, but generally it returns a server error.

Is the server experiencing problems?

```
curl 'https://rest.ensembl.org/lookup/id/ENSG00000157764?expand=1' -H 'Content-type:application/json'
```

```
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

**Comment by FlorianErger** [comment]
Yes, servers have been mostly down since yesterday. I'm having the same issues - we'll just have to wait until connectivity is restored.

**Comment by sgiorgetti** [comment]
Issue was fixed.

Closing this now.
